version: "3.8"

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "8002:8000"
    working_dir: /app
    command: python server.py
    volumes:
      - ./app:/app
      - ./data:/data
